server:
  port: 8083

###起个名字作为服务名称(该服务注册到eureka注册中心的名称，比如订单服务)
spring:
    application:
        name: app-order-feign

#开启hystrix断路器
feign:
  hystrix:
    enabled: true

###服务注册到eureka注册中心的地址
eureka:
  client:
    service-url:
           defaultZone: http://ysq:123456@127.0.0.1:8100/eureka
###因为该应用为服务提供者，是eureka的一个客户端，需要注册到注册中心
    register-with-eureka: true
###是否需要从eureka上检索服务
    fetch-registry: true
#  instance:
#      prefer-ip-address: false #将自己的ip注册到Eureka服务中,并改变其在注册中的地址
#      ip-address: 127.0.0.1
#      instance-id: ${spring.application.name}###${server.port} #指定实例id,改变其在注册中心的地址

###设置客户端的负载均衡策略
#app-item: #提供者的服务名称
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule